# This file has been generated by
# script/constant.pl enum ATTRIBUTEID constants

package OPCUA::Open62541::ATTRIBUTEID;

use 5.015004;
use strict;
use warnings;
use Carp;

our $VERSION = '0.006';

BEGIN {
    my $class = 'ATTRIBUTEID';

    # Even if we declare more than 10k constants, this is a fast way to do it.
    my $consts = <<'EOCONST';
NODEID 1
NODECLASS 2
BROWSENAME 3
DISPLAYNAME 4
DESCRIPTION 5
WRITEMASK 6
USERWRITEMASK 7
ISABSTRACT 8
SYMMETRIC 9
INVERSENAME 10
CONTAINSNOLOOPS 11
EVENTNOTIFIER 12
VALUE 13
DATATYPE 14
VALUERANK 15
ARRAYDIMENSIONS 16
ACCESSLEVEL 17
USERACCESSLEVEL 18
MINIMUMSAMPLINGINTERVAL 19
HISTORIZING 20
EXECUTABLE 21
USEREXECUTABLE 22
EOCONST

    open(my $fh, '<', \$consts) or croak "open consts: $!";

    local $_;
    my (%hash, $str, $num);
    while (<$fh>) {
	chomp;
	($str, $num) = split;
	$hash{"${class}_${str}"} = $num;
    }

    close($fh) or croak "close consts: $!";

    # This is how "use constant ..." creates constants.  constant.pm checks
    # constant names and non-existance internally.  We know our names are OK
    # and we only declare constants in our own namespace where they don't yet
    # exist.  Therefore we can skip the checks and make this module load
    # faster.
    no strict 'refs';    ## no critic (ProhibitNoStrict)
    my $symtab = \%{"OPCUA::Open62541::"};
    use strict;

    while (my ($name, $scalar) = each %hash) {
	Internals::SvREADONLY($scalar, 1);
	$symtab->{$name} = \$scalar;
    }
    mro::method_changed_in("OPCUA::Open62541");

    our @EXPORT_OK = keys %hash;
    our %EXPORT_TAGS = ($class => [keys %hash]);
}

1;

__END__

=head1 NAME

OPCUA::Open62541::ATTRIBUTEID - enum ATTRIBUTEID from constants.h

=head1 SYNOPSIS

  use OPCUA::Open62541;

  use OPCUA::Open62541 qw(ATTRIBUTEID_NODEID ...);

  use OPCUA::Open62541 ':ATTRIBUTEID';

=head1 DESCRIPTION

This module provides all ATTRIBUTEID enums as Perl constants.
They have been extracted from the constants.h C source file.

=head2 EXPORT

=over 4

=item ATTRIBUTEID_NODEID

=item ...

=item ATTRIBUTEID_USEREXECUTABLE

Export specific ATTRIBUTEID constants into the OPCUA::Open64541 name
space.

=item :ATTRIBUTEID

Exports all ATTRIBUTEID constants into the OPCUA::Open64541 name space.
You might want to import only the ones you need.

=back

=head1 SEE ALSO

OPCUA::Open62541

=head1 AUTHORS

Alexander Bluhm,
Arne Becker

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2020 Alexander Bluhm
Copyright (c) 2020 Arne Becker

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

Thanks to genua GmbH, https://www.genua.de/ for sponsoring this work.

=cut
