# This file has been generated by
# script/constant.pl enum CLIENTSTATE client_config

package OPCUA::Open62541::CLIENTSTATE;

use 5.015004;
use strict;
use warnings;
use Carp;

our $VERSION = '0.006';

BEGIN {
    my $class = 'CLIENTSTATE';

    # Even if we declare more than 10k constants, this is a fast way to do it.
    my $consts = <<'EOCONST';
DISCONNECTED 0
WAITING_FOR_ACK 1
CONNECTED 2
SECURECHANNEL 3
SESSION 4
SESSION_DISCONNECTED 5
SESSION_RENEWED 6
EOCONST

    open(my $fh, '<', \$consts) or croak "open consts: $!";

    local $_;
    my (%hash, $str, $num);
    while (<$fh>) {
	chomp;
	($str, $num) = split;
	$hash{"${class}_${str}"} = $num;
    }

    close($fh) or croak "close consts: $!";

    # This is how "use constant ..." creates constants.  constant.pm checks
    # constant names and non-existance internally.  We know our names are OK
    # and we only declare constants in our own namespace where they don't yet
    # exist.  Therefore we can skip the checks and make this module load
    # faster.
    no strict 'refs';    ## no critic (ProhibitNoStrict)
    my $symtab = \%{"OPCUA::Open62541::"};
    use strict;

    while (my ($name, $scalar) = each %hash) {
	Internals::SvREADONLY($scalar, 1);
	$symtab->{$name} = \$scalar;
    }
    mro::method_changed_in("OPCUA::Open62541");

    our @EXPORT_OK = keys %hash;
    our %EXPORT_TAGS = ($class => [keys %hash]);
}

1;

__END__

=head1 NAME

OPCUA::Open62541::CLIENTSTATE - enum CLIENTSTATE from client_config.h

=head1 SYNOPSIS

  use OPCUA::Open62541;

  use OPCUA::Open62541 qw(CLIENTSTATE_DISCONNECTED ...);

  use OPCUA::Open62541 ':CLIENTSTATE';

=head1 DESCRIPTION

This module provides all CLIENTSTATE enums as Perl constants.
They have been extracted from the client_config.h C source file.

=head2 EXPORT

=over 4

=item CLIENTSTATE_DISCONNECTED

=item ...

=item CLIENTSTATE_SESSION_RENEWED

Export specific CLIENTSTATE constants into the OPCUA::Open64541 name
space.

=item :CLIENTSTATE

Exports all CLIENTSTATE constants into the OPCUA::Open64541 name space.
You might want to import only the ones you need.

=back

=head1 SEE ALSO

OPCUA::Open62541

=head1 AUTHORS

Alexander Bluhm,
Arne Becker

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2020 Alexander Bluhm
Copyright (c) 2020 Arne Becker

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

Thanks to genua GmbH, https://www.genua.de/ for sponsoring this work.

=cut
