=pod

=head1 NAME

OPCUA::Open62541::Constant - export constants from open62541 to Perl

=head1 SYNOPSIS

  use OPCUA::Open62541;

  use OPCUA::Open62541 ':all';

  use OPCUA::Open62541 qw(:ATTRIBUTEID ...);

  use OPCUA::Open62541 qw(ORDER_LESS ORDER_EQ ORDER_MORE ...);

=head1 DESCRIPTION

This module provides all defines and enums from open62541 as Perl
constants.
They have been automatically extracted from the C header files.
Do not use this module directly, instead specify the export tag in
OPCUA::Open62541.

=head2 EXPORT

=over 4

=item :all

Export all constants.
You want to import only the ones you need.

=item :ATTRIBUTEID

=over 8

=item ATTRIBUTEID_NODEID

=item ATTRIBUTEID_NODECLASS

=item ATTRIBUTEID_BROWSENAME

=item ATTRIBUTEID_DISPLAYNAME

=item ATTRIBUTEID_DESCRIPTION

=item ATTRIBUTEID_WRITEMASK

=item ATTRIBUTEID_USERWRITEMASK

=item ATTRIBUTEID_ISABSTRACT

=item ATTRIBUTEID_SYMMETRIC

=item ATTRIBUTEID_INVERSENAME

=item ATTRIBUTEID_CONTAINSNOLOOPS

=item ATTRIBUTEID_EVENTNOTIFIER

=item ATTRIBUTEID_VALUE

=item ATTRIBUTEID_DATATYPE

=item ATTRIBUTEID_VALUERANK

=item ATTRIBUTEID_ARRAYDIMENSIONS

=item ATTRIBUTEID_ACCESSLEVEL

=item ATTRIBUTEID_USERACCESSLEVEL

=item ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL

=item ATTRIBUTEID_HISTORIZING

=item ATTRIBUTEID_EXECUTABLE

=item ATTRIBUTEID_USEREXECUTABLE

=back

=item :ACCESSLEVELMASK

=over 8

=item ACCESSLEVELMASK_READ

=item ACCESSLEVELMASK_WRITE

=item ACCESSLEVELMASK_HISTORYREAD

=item ACCESSLEVELMASK_HISTORYWRITE

=item ACCESSLEVELMASK_SEMANTICCHANGE

=item ACCESSLEVELMASK_STATUSWRITE

=item ACCESSLEVELMASK_TIMESTAMPWRITE

=back

=item :WRITEMASK

=over 8

=item WRITEMASK_ACCESSLEVEL

=item WRITEMASK_ARRRAYDIMENSIONS

=item WRITEMASK_BROWSENAME

=item WRITEMASK_CONTAINSNOLOOPS

=item WRITEMASK_DATATYPE

=item WRITEMASK_DESCRIPTION

=item WRITEMASK_DISPLAYNAME

=item WRITEMASK_EVENTNOTIFIER

=item WRITEMASK_EXECUTABLE

=item WRITEMASK_HISTORIZING

=item WRITEMASK_INVERSENAME

=item WRITEMASK_ISABSTRACT

=item WRITEMASK_MINIMUMSAMPLINGINTERVAL

=item WRITEMASK_NODECLASS

=item WRITEMASK_NODEID

=item WRITEMASK_SYMMETRIC

=item WRITEMASK_USERACCESSLEVEL

=item WRITEMASK_USEREXECUTABLE

=item WRITEMASK_USERWRITEMASK

=item WRITEMASK_VALUERANK

=item WRITEMASK_WRITEMASK

=item WRITEMASK_VALUEFORVARIABLETYPE

=back

=item :VALUERANK

=over 8

=item VALUERANK_SCALAR_OR_ONE_DIMENSION

=item VALUERANK_ANY

=item VALUERANK_SCALAR

=item VALUERANK_ONE_OR_MORE_DIMENSIONS

=item VALUERANK_ONE_DIMENSION

=item VALUERANK_TWO_DIMENSIONS

=item VALUERANK_THREE_DIMENSIONS

=back

=item :RULEHANDLING

=over 8

=item RULEHANDLING_DEFAULT

=item RULEHANDLING_ABORT

=item RULEHANDLING_WARN

=item RULEHANDLING_ACCEPT

=back

=item :ORDER

=over 8

=item ORDER_LESS

=item ORDER_EQ

=item ORDER_MORE

=back

=item :VARIANT

=over 8

=item VARIANT_DATA

=item VARIANT_DATA_NODELETE

=back

=item :STATUSCODE

=over 8

=item STATUSCODE_GOOD

=item STATUSCODE_INFOTYPE_DATAVALUE

=item STATUSCODE_INFOBITS_OVERFLOW

=item STATUSCODE_BADUNEXPECTEDERROR

=item STATUSCODE_BADINTERNALERROR

=item STATUSCODE_BADOUTOFMEMORY

=item STATUSCODE_BADRESOURCEUNAVAILABLE

=item STATUSCODE_BADCOMMUNICATIONERROR

=item STATUSCODE_BADENCODINGERROR

=item STATUSCODE_BADDECODINGERROR

=item STATUSCODE_BADENCODINGLIMITSEXCEEDED

=item STATUSCODE_BADREQUESTTOOLARGE

=item STATUSCODE_BADRESPONSETOOLARGE

=item STATUSCODE_BADUNKNOWNRESPONSE

=item STATUSCODE_BADTIMEOUT

=item STATUSCODE_BADSERVICEUNSUPPORTED

=item STATUSCODE_BADSHUTDOWN

=item STATUSCODE_BADSERVERNOTCONNECTED

=item STATUSCODE_BADSERVERHALTED

=item STATUSCODE_BADNOTHINGTODO

=item STATUSCODE_BADTOOMANYOPERATIONS

=item STATUSCODE_BADTOOMANYMONITOREDITEMS

=item STATUSCODE_BADDATATYPEIDUNKNOWN

=item STATUSCODE_BADCERTIFICATEINVALID

=item STATUSCODE_BADSECURITYCHECKSFAILED

=item STATUSCODE_BADCERTIFICATEPOLICYCHECKFAILED

=item STATUSCODE_BADCERTIFICATETIMEINVALID

=item STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID

=item STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID

=item STATUSCODE_BADCERTIFICATEURIINVALID

=item STATUSCODE_BADCERTIFICATEUSENOTALLOWED

=item STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED

=item STATUSCODE_BADCERTIFICATEUNTRUSTED

=item STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN

=item STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN

=item STATUSCODE_BADCERTIFICATEREVOKED

=item STATUSCODE_BADCERTIFICATEISSUERREVOKED

=item STATUSCODE_BADCERTIFICATECHAININCOMPLETE

=item STATUSCODE_BADUSERACCESSDENIED

=item STATUSCODE_BADIDENTITYTOKENINVALID

=item STATUSCODE_BADIDENTITYTOKENREJECTED

=item STATUSCODE_BADSECURECHANNELIDINVALID

=item STATUSCODE_BADINVALIDTIMESTAMP

=item STATUSCODE_BADNONCEINVALID

=item STATUSCODE_BADSESSIONIDINVALID

=item STATUSCODE_BADSESSIONCLOSED

=item STATUSCODE_BADSESSIONNOTACTIVATED

=item STATUSCODE_BADSUBSCRIPTIONIDINVALID

=item STATUSCODE_BADREQUESTHEADERINVALID

=item STATUSCODE_BADTIMESTAMPSTORETURNINVALID

=item STATUSCODE_BADREQUESTCANCELLEDBYCLIENT

=item STATUSCODE_BADTOOMANYARGUMENTS

=item STATUSCODE_BADLICENSEEXPIRED

=item STATUSCODE_BADLICENSELIMITSEXCEEDED

=item STATUSCODE_BADLICENSENOTAVAILABLE

=item STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED

=item STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY

=item STATUSCODE_GOODOVERLOAD

=item STATUSCODE_GOODCLAMPED

=item STATUSCODE_BADNOCOMMUNICATION

=item STATUSCODE_BADWAITINGFORINITIALDATA

=item STATUSCODE_BADNODEIDINVALID

=item STATUSCODE_BADNODEIDUNKNOWN

=item STATUSCODE_BADATTRIBUTEIDINVALID

=item STATUSCODE_BADINDEXRANGEINVALID

=item STATUSCODE_BADINDEXRANGENODATA

=item STATUSCODE_BADDATAENCODINGINVALID

=item STATUSCODE_BADDATAENCODINGUNSUPPORTED

=item STATUSCODE_BADNOTREADABLE

=item STATUSCODE_BADNOTWRITABLE

=item STATUSCODE_BADOUTOFRANGE

=item STATUSCODE_BADNOTSUPPORTED

=item STATUSCODE_BADNOTFOUND

=item STATUSCODE_BADOBJECTDELETED

=item STATUSCODE_BADNOTIMPLEMENTED

=item STATUSCODE_BADMONITORINGMODEINVALID

=item STATUSCODE_BADMONITOREDITEMIDINVALID

=item STATUSCODE_BADMONITOREDITEMFILTERINVALID

=item STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED

=item STATUSCODE_BADFILTERNOTALLOWED

=item STATUSCODE_BADSTRUCTUREMISSING

=item STATUSCODE_BADEVENTFILTERINVALID

=item STATUSCODE_BADCONTENTFILTERINVALID

=item STATUSCODE_BADFILTEROPERATORINVALID

=item STATUSCODE_BADFILTEROPERATORUNSUPPORTED

=item STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH

=item STATUSCODE_BADFILTEROPERANDINVALID

=item STATUSCODE_BADFILTERELEMENTINVALID

=item STATUSCODE_BADFILTERLITERALINVALID

=item STATUSCODE_BADCONTINUATIONPOINTINVALID

=item STATUSCODE_BADNOCONTINUATIONPOINTS

=item STATUSCODE_BADREFERENCETYPEIDINVALID

=item STATUSCODE_BADBROWSEDIRECTIONINVALID

=item STATUSCODE_BADNODENOTINVIEW

=item STATUSCODE_BADNUMERICOVERFLOW

=item STATUSCODE_BADSERVERURIINVALID

=item STATUSCODE_BADSERVERNAMEMISSING

=item STATUSCODE_BADDISCOVERYURLMISSING

=item STATUSCODE_BADSEMPAHOREFILEMISSING

=item STATUSCODE_BADREQUESTTYPEINVALID

=item STATUSCODE_BADSECURITYMODEREJECTED

=item STATUSCODE_BADSECURITYPOLICYREJECTED

=item STATUSCODE_BADTOOMANYSESSIONS

=item STATUSCODE_BADUSERSIGNATUREINVALID

=item STATUSCODE_BADAPPLICATIONSIGNATUREINVALID

=item STATUSCODE_BADNOVALIDCERTIFICATES

=item STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED

=item STATUSCODE_BADREQUESTCANCELLEDBYREQUEST

=item STATUSCODE_BADPARENTNODEIDINVALID

=item STATUSCODE_BADREFERENCENOTALLOWED

=item STATUSCODE_BADNODEIDREJECTED

=item STATUSCODE_BADNODEIDEXISTS

=item STATUSCODE_BADNODECLASSINVALID

=item STATUSCODE_BADBROWSENAMEINVALID

=item STATUSCODE_BADBROWSENAMEDUPLICATED

=item STATUSCODE_BADNODEATTRIBUTESINVALID

=item STATUSCODE_BADTYPEDEFINITIONINVALID

=item STATUSCODE_BADSOURCENODEIDINVALID

=item STATUSCODE_BADTARGETNODEIDINVALID

=item STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED

=item STATUSCODE_BADINVALIDSELFREFERENCE

=item STATUSCODE_BADREFERENCELOCALONLY

=item STATUSCODE_BADNODELETERIGHTS

=item STATUSCODE_UNCERTAINREFERENCENOTDELETED

=item STATUSCODE_BADSERVERINDEXINVALID

=item STATUSCODE_BADVIEWIDUNKNOWN

=item STATUSCODE_BADVIEWTIMESTAMPINVALID

=item STATUSCODE_BADVIEWPARAMETERMISMATCH

=item STATUSCODE_BADVIEWVERSIONINVALID

=item STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE

=item STATUSCODE_GOODRESULTSMAYBEINCOMPLETE

=item STATUSCODE_BADNOTTYPEDEFINITION

=item STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER

=item STATUSCODE_BADTOOMANYMATCHES

=item STATUSCODE_BADQUERYTOOCOMPLEX

=item STATUSCODE_BADNOMATCH

=item STATUSCODE_BADMAXAGEINVALID

=item STATUSCODE_BADSECURITYMODEINSUFFICIENT

=item STATUSCODE_BADHISTORYOPERATIONINVALID

=item STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED

=item STATUSCODE_BADINVALIDTIMESTAMPARGUMENT

=item STATUSCODE_BADWRITENOTSUPPORTED

=item STATUSCODE_BADTYPEMISMATCH

=item STATUSCODE_BADMETHODINVALID

=item STATUSCODE_BADARGUMENTSMISSING

=item STATUSCODE_BADNOTEXECUTABLE

=item STATUSCODE_BADTOOMANYSUBSCRIPTIONS

=item STATUSCODE_BADTOOMANYPUBLISHREQUESTS

=item STATUSCODE_BADNOSUBSCRIPTION

=item STATUSCODE_BADSEQUENCENUMBERUNKNOWN

=item STATUSCODE_BADMESSAGENOTAVAILABLE

=item STATUSCODE_BADINSUFFICIENTCLIENTPROFILE

=item STATUSCODE_BADSTATENOTACTIVE

=item STATUSCODE_BADALREADYEXISTS

=item STATUSCODE_BADTCPSERVERTOOBUSY

=item STATUSCODE_BADTCPMESSAGETYPEINVALID

=item STATUSCODE_BADTCPSECURECHANNELUNKNOWN

=item STATUSCODE_BADTCPMESSAGETOOLARGE

=item STATUSCODE_BADTCPNOTENOUGHRESOURCES

=item STATUSCODE_BADTCPINTERNALERROR

=item STATUSCODE_BADTCPENDPOINTURLINVALID

=item STATUSCODE_BADREQUESTINTERRUPTED

=item STATUSCODE_BADREQUESTTIMEOUT

=item STATUSCODE_BADSECURECHANNELCLOSED

=item STATUSCODE_BADSECURECHANNELTOKENUNKNOWN

=item STATUSCODE_BADSEQUENCENUMBERINVALID

=item STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED

=item STATUSCODE_BADCONFIGURATIONERROR

=item STATUSCODE_BADNOTCONNECTED

=item STATUSCODE_BADDEVICEFAILURE

=item STATUSCODE_BADSENSORFAILURE

=item STATUSCODE_BADOUTOFSERVICE

=item STATUSCODE_BADDEADBANDFILTERINVALID

=item STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE

=item STATUSCODE_UNCERTAINLASTUSABLEVALUE

=item STATUSCODE_UNCERTAINSUBSTITUTEVALUE

=item STATUSCODE_UNCERTAININITIALVALUE

=item STATUSCODE_UNCERTAINSENSORNOTACCURATE

=item STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED

=item STATUSCODE_UNCERTAINSUBNORMAL

=item STATUSCODE_GOODLOCALOVERRIDE

=item STATUSCODE_BADREFRESHINPROGRESS

=item STATUSCODE_BADCONDITIONALREADYDISABLED

=item STATUSCODE_BADCONDITIONALREADYENABLED

=item STATUSCODE_BADCONDITIONDISABLED

=item STATUSCODE_BADEVENTIDUNKNOWN

=item STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE

=item STATUSCODE_BADDIALOGNOTACTIVE

=item STATUSCODE_BADDIALOGRESPONSEINVALID

=item STATUSCODE_BADCONDITIONBRANCHALREADYACKED

=item STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED

=item STATUSCODE_BADCONDITIONALREADYSHELVED

=item STATUSCODE_BADCONDITIONNOTSHELVED

=item STATUSCODE_BADSHELVINGTIMEOUTOFRANGE

=item STATUSCODE_BADNODATA

=item STATUSCODE_BADBOUNDNOTFOUND

=item STATUSCODE_BADBOUNDNOTSUPPORTED

=item STATUSCODE_BADDATALOST

=item STATUSCODE_BADDATAUNAVAILABLE

=item STATUSCODE_BADENTRYEXISTS

=item STATUSCODE_BADNOENTRYEXISTS

=item STATUSCODE_BADTIMESTAMPNOTSUPPORTED

=item STATUSCODE_GOODENTRYINSERTED

=item STATUSCODE_GOODENTRYREPLACED

=item STATUSCODE_UNCERTAINDATASUBNORMAL

=item STATUSCODE_GOODNODATA

=item STATUSCODE_GOODMOREDATA

=item STATUSCODE_BADAGGREGATELISTMISMATCH

=item STATUSCODE_BADAGGREGATENOTSUPPORTED

=item STATUSCODE_BADAGGREGATEINVALIDINPUTS

=item STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED

=item STATUSCODE_GOODDATAIGNORED

=item STATUSCODE_BADREQUESTNOTALLOWED

=item STATUSCODE_BADREQUESTNOTCOMPLETE

=item STATUSCODE_GOODEDITED

=item STATUSCODE_GOODPOSTACTIONFAILED

=item STATUSCODE_UNCERTAINDOMINANTVALUECHANGED

=item STATUSCODE_GOODDEPENDENTVALUECHANGED

=item STATUSCODE_BADDOMINANTVALUECHANGED

=item STATUSCODE_UNCERTAINDEPENDENTVALUECHANGED

=item STATUSCODE_BADDEPENDENTVALUECHANGED

=item STATUSCODE_GOODCOMMUNICATIONEVENT

=item STATUSCODE_GOODSHUTDOWNEVENT

=item STATUSCODE_GOODCALLAGAIN

=item STATUSCODE_GOODNONCRITICALTIMEOUT

=item STATUSCODE_BADINVALIDARGUMENT

=item STATUSCODE_BADCONNECTIONREJECTED

=item STATUSCODE_BADDISCONNECT

=item STATUSCODE_BADCONNECTIONCLOSED

=item STATUSCODE_BADINVALIDSTATE

=item STATUSCODE_BADENDOFSTREAM

=item STATUSCODE_BADNODATAAVAILABLE

=item STATUSCODE_BADWAITINGFORRESPONSE

=item STATUSCODE_BADOPERATIONABANDONED

=item STATUSCODE_BADEXPECTEDSTREAMTOBLOCK

=item STATUSCODE_BADWOULDBLOCK

=item STATUSCODE_BADSYNTAXERROR

=item STATUSCODE_BADMAXCONNECTIONSREACHED

=back

=item :BROWSERESULTMASK

=over 8

=item BROWSERESULTMASK_NONE

=item BROWSERESULTMASK_REFERENCETYPEID

=item BROWSERESULTMASK_ISFORWARD

=item BROWSERESULTMASK_NODECLASS

=item BROWSERESULTMASK_BROWSENAME

=item BROWSERESULTMASK_DISPLAYNAME

=item BROWSERESULTMASK_TYPEDEFINITION

=item BROWSERESULTMASK_ALL

=item BROWSERESULTMASK_REFERENCETYPEINFO

=item BROWSERESULTMASK_TARGETINFO

=back

=item :CLIENTSTATE

=over 8

=item CLIENTSTATE_DISCONNECTED

=item CLIENTSTATE_WAITING_FOR_ACK

=item CLIENTSTATE_CONNECTED

=item CLIENTSTATE_SECURECHANNEL

=item CLIENTSTATE_SESSION

=item CLIENTSTATE_SESSION_DISCONNECTED

=item CLIENTSTATE_SESSION_RENEWED

=back

=item :NODEIDTYPE

=over 8

=item NODEIDTYPE_NUMERIC

=item NODEIDTYPE_STRING

=item NODEIDTYPE_GUID

=item NODEIDTYPE_BYTESTRING

=back

=item :TYPES

=over 8

=item TYPES_COUNT

=item TYPES_BOOLEAN

=item TYPES_SBYTE

=item TYPES_BYTE

=item TYPES_INT16

=item TYPES_UINT16

=item TYPES_INT32

=item TYPES_UINT32

=item TYPES_INT64

=item TYPES_UINT64

=item TYPES_FLOAT

=item TYPES_DOUBLE

=item TYPES_STRING

=item TYPES_DATETIME

=item TYPES_GUID

=item TYPES_BYTESTRING

=item TYPES_XMLELEMENT

=item TYPES_NODEID

=item TYPES_EXPANDEDNODEID

=item TYPES_STATUSCODE

=item TYPES_QUALIFIEDNAME

=item TYPES_LOCALIZEDTEXT

=item TYPES_EXTENSIONOBJECT

=item TYPES_DATAVALUE

=item TYPES_VARIANT

=item TYPES_DIAGNOSTICINFO

=item TYPES_NODECLASS

=item TYPES_ARGUMENT

=item TYPES_ENUMVALUETYPE

=item TYPES_DURATION

=item TYPES_UTCTIME

=item TYPES_LOCALEID

=item TYPES_APPLICATIONTYPE

=item TYPES_APPLICATIONDESCRIPTION

=item TYPES_REQUESTHEADER

=item TYPES_RESPONSEHEADER

=item TYPES_SERVICEFAULT

=item TYPES_FINDSERVERSREQUEST

=item TYPES_FINDSERVERSRESPONSE

=item TYPES_SERVERONNETWORK

=item TYPES_FINDSERVERSONNETWORKREQUEST

=item TYPES_FINDSERVERSONNETWORKRESPONSE

=item TYPES_MESSAGESECURITYMODE

=item TYPES_USERTOKENTYPE

=item TYPES_USERTOKENPOLICY

=item TYPES_ENDPOINTDESCRIPTION

=item TYPES_GETENDPOINTSREQUEST

=item TYPES_GETENDPOINTSRESPONSE

=item TYPES_REGISTEREDSERVER

=item TYPES_REGISTERSERVERREQUEST

=item TYPES_REGISTERSERVERRESPONSE

=item TYPES_DISCOVERYCONFIGURATION

=item TYPES_MDNSDISCOVERYCONFIGURATION

=item TYPES_REGISTERSERVER2REQUEST

=item TYPES_REGISTERSERVER2RESPONSE

=item TYPES_SECURITYTOKENREQUESTTYPE

=item TYPES_CHANNELSECURITYTOKEN

=item TYPES_OPENSECURECHANNELREQUEST

=item TYPES_OPENSECURECHANNELRESPONSE

=item TYPES_CLOSESECURECHANNELREQUEST

=item TYPES_CLOSESECURECHANNELRESPONSE

=item TYPES_SIGNEDSOFTWARECERTIFICATE

=item TYPES_SIGNATUREDATA

=item TYPES_CREATESESSIONREQUEST

=item TYPES_CREATESESSIONRESPONSE

=item TYPES_USERIDENTITYTOKEN

=item TYPES_ANONYMOUSIDENTITYTOKEN

=item TYPES_USERNAMEIDENTITYTOKEN

=item TYPES_X509IDENTITYTOKEN

=item TYPES_ISSUEDIDENTITYTOKEN

=item TYPES_ACTIVATESESSIONREQUEST

=item TYPES_ACTIVATESESSIONRESPONSE

=item TYPES_CLOSESESSIONREQUEST

=item TYPES_CLOSESESSIONRESPONSE

=item TYPES_NODEATTRIBUTESMASK

=item TYPES_NODEATTRIBUTES

=item TYPES_OBJECTATTRIBUTES

=item TYPES_VARIABLEATTRIBUTES

=item TYPES_METHODATTRIBUTES

=item TYPES_OBJECTTYPEATTRIBUTES

=item TYPES_VARIABLETYPEATTRIBUTES

=item TYPES_REFERENCETYPEATTRIBUTES

=item TYPES_DATATYPEATTRIBUTES

=item TYPES_VIEWATTRIBUTES

=item TYPES_ADDNODESITEM

=item TYPES_ADDNODESRESULT

=item TYPES_ADDNODESREQUEST

=item TYPES_ADDNODESRESPONSE

=item TYPES_ADDREFERENCESITEM

=item TYPES_ADDREFERENCESREQUEST

=item TYPES_ADDREFERENCESRESPONSE

=item TYPES_DELETENODESITEM

=item TYPES_DELETENODESREQUEST

=item TYPES_DELETENODESRESPONSE

=item TYPES_DELETEREFERENCESITEM

=item TYPES_DELETEREFERENCESREQUEST

=item TYPES_DELETEREFERENCESRESPONSE

=item TYPES_BROWSEDIRECTION

=item TYPES_VIEWDESCRIPTION

=item TYPES_BROWSEDESCRIPTION

=item TYPES_BROWSERESULTMASK

=item TYPES_REFERENCEDESCRIPTION

=item TYPES_BROWSERESULT

=item TYPES_BROWSEREQUEST

=item TYPES_BROWSERESPONSE

=item TYPES_BROWSENEXTREQUEST

=item TYPES_BROWSENEXTRESPONSE

=item TYPES_RELATIVEPATHELEMENT

=item TYPES_RELATIVEPATH

=item TYPES_BROWSEPATH

=item TYPES_BROWSEPATHTARGET

=item TYPES_BROWSEPATHRESULT

=item TYPES_TRANSLATEBROWSEPATHSTONODEIDSREQUEST

=item TYPES_TRANSLATEBROWSEPATHSTONODEIDSRESPONSE

=item TYPES_REGISTERNODESREQUEST

=item TYPES_REGISTERNODESRESPONSE

=item TYPES_UNREGISTERNODESREQUEST

=item TYPES_UNREGISTERNODESRESPONSE

=item TYPES_FILTEROPERATOR

=item TYPES_CONTENTFILTERELEMENT

=item TYPES_CONTENTFILTER

=item TYPES_FILTEROPERAND

=item TYPES_ELEMENTOPERAND

=item TYPES_LITERALOPERAND

=item TYPES_ATTRIBUTEOPERAND

=item TYPES_SIMPLEATTRIBUTEOPERAND

=item TYPES_CONTENTFILTERELEMENTRESULT

=item TYPES_CONTENTFILTERRESULT

=item TYPES_TIMESTAMPSTORETURN

=item TYPES_READVALUEID

=item TYPES_READREQUEST

=item TYPES_READRESPONSE

=item TYPES_WRITEVALUE

=item TYPES_WRITEREQUEST

=item TYPES_WRITERESPONSE

=item TYPES_CALLMETHODREQUEST

=item TYPES_CALLMETHODRESULT

=item TYPES_CALLREQUEST

=item TYPES_CALLRESPONSE

=item TYPES_MONITORINGMODE

=item TYPES_DATACHANGETRIGGER

=item TYPES_DEADBANDTYPE

=item TYPES_DATACHANGEFILTER

=item TYPES_EVENTFILTER

=item TYPES_AGGREGATECONFIGURATION

=item TYPES_AGGREGATEFILTER

=item TYPES_EVENTFILTERRESULT

=item TYPES_MONITORINGPARAMETERS

=item TYPES_MONITOREDITEMCREATEREQUEST

=item TYPES_MONITOREDITEMCREATERESULT

=item TYPES_CREATEMONITOREDITEMSREQUEST

=item TYPES_CREATEMONITOREDITEMSRESPONSE

=item TYPES_MONITOREDITEMMODIFYREQUEST

=item TYPES_MONITOREDITEMMODIFYRESULT

=item TYPES_MODIFYMONITOREDITEMSREQUEST

=item TYPES_MODIFYMONITOREDITEMSRESPONSE

=item TYPES_SETMONITORINGMODEREQUEST

=item TYPES_SETMONITORINGMODERESPONSE

=item TYPES_SETTRIGGERINGREQUEST

=item TYPES_SETTRIGGERINGRESPONSE

=item TYPES_DELETEMONITOREDITEMSREQUEST

=item TYPES_DELETEMONITOREDITEMSRESPONSE

=item TYPES_CREATESUBSCRIPTIONREQUEST

=item TYPES_CREATESUBSCRIPTIONRESPONSE

=item TYPES_MODIFYSUBSCRIPTIONREQUEST

=item TYPES_MODIFYSUBSCRIPTIONRESPONSE

=item TYPES_SETPUBLISHINGMODEREQUEST

=item TYPES_SETPUBLISHINGMODERESPONSE

=item TYPES_NOTIFICATIONMESSAGE

=item TYPES_MONITOREDITEMNOTIFICATION

=item TYPES_EVENTFIELDLIST

=item TYPES_STATUSCHANGENOTIFICATION

=item TYPES_SUBSCRIPTIONACKNOWLEDGEMENT

=item TYPES_PUBLISHREQUEST

=item TYPES_PUBLISHRESPONSE

=item TYPES_REPUBLISHREQUEST

=item TYPES_REPUBLISHRESPONSE

=item TYPES_DELETESUBSCRIPTIONSREQUEST

=item TYPES_DELETESUBSCRIPTIONSRESPONSE

=item TYPES_BUILDINFO

=item TYPES_REDUNDANCYSUPPORT

=item TYPES_SERVERSTATE

=item TYPES_SERVERDIAGNOSTICSSUMMARYDATATYPE

=item TYPES_SERVERSTATUSDATATYPE

=item TYPES_RANGE

=item TYPES_DATACHANGENOTIFICATION

=item TYPES_EVENTNOTIFICATIONLIST

=back

=back

=head1 SEE ALSO

OPCUA::Open62541

=head1 AUTHORS

Alexander Bluhm,
Arne Becker

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2020 Alexander Bluhm
Copyright (c) 2020 Arne Becker

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

Thanks to genua GmbH, https://www.genua.de/ for sponsoring this work.

=cut
