name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Test (${{matrix.config.v}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {v: 'v1.3.17'}
          - {v: 'v1.3.18'}
          - {v: '1.3'}
# logger in 1.4 does not compile due to different storage life time
#          - {v: '1.4'}
# the master runner does not terminate currently
# disable for now until we have time to investigate
#          - {v: 'master'}
    steps:
    - uses: actions/checkout@v7
    - name: Cache and install packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >-
          gpg
          make
          git
          build-essential
          gcc
          pkg-config
          cmake
          libmbedtls-dev
          libssl-dev
          net-tools
          libdevel-checklib-perl
          libio-socket-ssl-perl
          libsocket6-perl
          libtest-deep-perl
          libtest-eol-perl
          libtest-exception-perl
          libtest-leaktrace-perl
          libtest-nowarnings-perl
          libtest-perl-critic-perl
          libtest-pod-perl
          libtest-requires-perl
          libtest-strict-perl
          libtest-tcp-perl
          libtest-warn-perl
          libyaml-tiny-perl
        version: 1.0
    - name: Install open62541
      run: |
        cd /tmp
        git clone https://github.com/open62541/open62541
        cd open62541
        git checkout ${{matrix.config.v}}
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL -DUA_ENABLE_ENCRYPTION=OPENSSL ..
        make
        sudo make install
        sudo ldconfig /usr/local/lib
    - name: Perl Makefile
      run: perl Makefile.PL
    - name: Make
      run: make
    - name: Test
      run: make test
