package OPCUA::Open62541;

use 5.030001;
use strict;
use warnings;

require Exporter;

our @ISA = qw(Exporter);

# Items to export into callers namespace by default. Note: do not export
# names by default without a very good reason. Use EXPORT_OK instead.
# Do not simply export all your public functions/methods/constants.

# This allows declaration	use OPCUA::Open62541 ':all';
# If you do not need this, moving things directly into @EXPORT or @EXPORT_OK
# will save memory.
our %EXPORT_TAGS = ( 'all' => [ qw(
	
) ] );

our @EXPORT_OK = ( @{ $EXPORT_TAGS{'all'} } );

our @EXPORT = qw(

    TRUE
    FALSE
    SBYTE_MIN
    SBYTE_MAX
    BYTE_MIN
    BYTE_MAX
    INT16_MIN
    INT16_MAX
    UINT16_MIN
    UINT16_MAX
    INT32_MIN
    INT32_MAX
    UINT32_MIN
    UINT32_MAX
    INT64_MIN
    INT64_MAX
    UINT64_MIN
    UINT64_MAX

    STATUSCODE_GOOD
    STATUSCODE_INFOTYPE_DATAVALUE
    STATUSCODE_INFOBITS_OVERFLOW
    STATUSCODE_BADUNEXPECTEDERROR
    STATUSCODE_BADINTERNALERROR
    STATUSCODE_BADOUTOFMEMORY
    STATUSCODE_BADRESOURCEUNAVAILABLE
    STATUSCODE_BADCOMMUNICATIONERROR
    STATUSCODE_BADENCODINGERROR
    STATUSCODE_BADDECODINGERROR
    STATUSCODE_BADENCODINGLIMITSEXCEEDED
    STATUSCODE_BADREQUESTTOOLARGE
    STATUSCODE_BADRESPONSETOOLARGE
    STATUSCODE_BADUNKNOWNRESPONSE
    STATUSCODE_BADTIMEOUT
    STATUSCODE_BADSERVICEUNSUPPORTED
    STATUSCODE_BADSHUTDOWN
    STATUSCODE_BADSERVERNOTCONNECTED
    STATUSCODE_BADSERVERHALTED
    STATUSCODE_BADNOTHINGTODO
    STATUSCODE_BADTOOMANYOPERATIONS
    STATUSCODE_BADTOOMANYMONITOREDITEMS
    STATUSCODE_BADDATATYPEIDUNKNOWN
    STATUSCODE_BADCERTIFICATEINVALID
    STATUSCODE_BADSECURITYCHECKSFAILED
    STATUSCODE_BADCERTIFICATEPOLICYCHECKFAILED
    STATUSCODE_BADCERTIFICATETIMEINVALID
    STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID
    STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID
    STATUSCODE_BADCERTIFICATEURIINVALID
    STATUSCODE_BADCERTIFICATEUSENOTALLOWED
    STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED
    STATUSCODE_BADCERTIFICATEUNTRUSTED
    STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN
    STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN
    STATUSCODE_BADCERTIFICATEREVOKED
    STATUSCODE_BADCERTIFICATEISSUERREVOKED
    STATUSCODE_BADCERTIFICATECHAININCOMPLETE
    STATUSCODE_BADUSERACCESSDENIED
    STATUSCODE_BADIDENTITYTOKENINVALID
    STATUSCODE_BADIDENTITYTOKENREJECTED
    STATUSCODE_BADSECURECHANNELIDINVALID
    STATUSCODE_BADINVALIDTIMESTAMP
    STATUSCODE_BADNONCEINVALID
    STATUSCODE_BADSESSIONIDINVALID
    STATUSCODE_BADSESSIONCLOSED
    STATUSCODE_BADSESSIONNOTACTIVATED
    STATUSCODE_BADSUBSCRIPTIONIDINVALID
    STATUSCODE_BADREQUESTHEADERINVALID
    STATUSCODE_BADTIMESTAMPSTORETURNINVALID
    STATUSCODE_BADREQUESTCANCELLEDBYCLIENT
    STATUSCODE_BADTOOMANYARGUMENTS
    STATUSCODE_BADLICENSEEXPIRED
    STATUSCODE_BADLICENSELIMITSEXCEEDED
    STATUSCODE_BADLICENSENOTAVAILABLE
    STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED
    STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY
    STATUSCODE_GOODOVERLOAD
    STATUSCODE_GOODCLAMPED
    STATUSCODE_BADNOCOMMUNICATION
    STATUSCODE_BADWAITINGFORINITIALDATA
    STATUSCODE_BADNODEIDINVALID
    STATUSCODE_BADNODEIDUNKNOWN
    STATUSCODE_BADATTRIBUTEIDINVALID
    STATUSCODE_BADINDEXRANGEINVALID
    STATUSCODE_BADINDEXRANGENODATA
    STATUSCODE_BADDATAENCODINGINVALID
    STATUSCODE_BADDATAENCODINGUNSUPPORTED
    STATUSCODE_BADNOTREADABLE
    STATUSCODE_BADNOTWRITABLE
    STATUSCODE_BADOUTOFRANGE
    STATUSCODE_BADNOTSUPPORTED
    STATUSCODE_BADNOTFOUND
    STATUSCODE_BADOBJECTDELETED
    STATUSCODE_BADNOTIMPLEMENTED
    STATUSCODE_BADMONITORINGMODEINVALID
    STATUSCODE_BADMONITOREDITEMIDINVALID
    STATUSCODE_BADMONITOREDITEMFILTERINVALID
    STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED
    STATUSCODE_BADFILTERNOTALLOWED
    STATUSCODE_BADSTRUCTUREMISSING
    STATUSCODE_BADEVENTFILTERINVALID
    STATUSCODE_BADCONTENTFILTERINVALID
    STATUSCODE_BADFILTEROPERATORINVALID
    STATUSCODE_BADFILTEROPERATORUNSUPPORTED
    STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH
    STATUSCODE_BADFILTEROPERANDINVALID
    STATUSCODE_BADFILTERELEMENTINVALID
    STATUSCODE_BADFILTERLITERALINVALID
    STATUSCODE_BADCONTINUATIONPOINTINVALID
    STATUSCODE_BADNOCONTINUATIONPOINTS
    STATUSCODE_BADREFERENCETYPEIDINVALID
    STATUSCODE_BADBROWSEDIRECTIONINVALID
    STATUSCODE_BADNODENOTINVIEW
    STATUSCODE_BADNUMERICOVERFLOW
    STATUSCODE_BADSERVERURIINVALID
    STATUSCODE_BADSERVERNAMEMISSING
    STATUSCODE_BADDISCOVERYURLMISSING
    STATUSCODE_BADSEMPAHOREFILEMISSING
    STATUSCODE_BADREQUESTTYPEINVALID
    STATUSCODE_BADSECURITYMODEREJECTED
    STATUSCODE_BADSECURITYPOLICYREJECTED
    STATUSCODE_BADTOOMANYSESSIONS
    STATUSCODE_BADUSERSIGNATUREINVALID
    STATUSCODE_BADAPPLICATIONSIGNATUREINVALID
    STATUSCODE_BADNOVALIDCERTIFICATES
    STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED
    STATUSCODE_BADREQUESTCANCELLEDBYREQUEST
    STATUSCODE_BADPARENTNODEIDINVALID
    STATUSCODE_BADREFERENCENOTALLOWED
    STATUSCODE_BADNODEIDREJECTED
    STATUSCODE_BADNODEIDEXISTS
    STATUSCODE_BADNODECLASSINVALID
    STATUSCODE_BADBROWSENAMEINVALID
    STATUSCODE_BADBROWSENAMEDUPLICATED
    STATUSCODE_BADNODEATTRIBUTESINVALID
    STATUSCODE_BADTYPEDEFINITIONINVALID
    STATUSCODE_BADSOURCENODEIDINVALID
    STATUSCODE_BADTARGETNODEIDINVALID
    STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED
    STATUSCODE_BADINVALIDSELFREFERENCE
    STATUSCODE_BADREFERENCELOCALONLY
    STATUSCODE_BADNODELETERIGHTS
    STATUSCODE_UNCERTAINREFERENCENOTDELETED
    STATUSCODE_BADSERVERINDEXINVALID
    STATUSCODE_BADVIEWIDUNKNOWN
    STATUSCODE_BADVIEWTIMESTAMPINVALID
    STATUSCODE_BADVIEWPARAMETERMISMATCH
    STATUSCODE_BADVIEWVERSIONINVALID
    STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE
    STATUSCODE_GOODRESULTSMAYBEINCOMPLETE
    STATUSCODE_BADNOTTYPEDEFINITION
    STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER
    STATUSCODE_BADTOOMANYMATCHES
    STATUSCODE_BADQUERYTOOCOMPLEX
    STATUSCODE_BADNOMATCH
    STATUSCODE_BADMAXAGEINVALID
    STATUSCODE_BADSECURITYMODEINSUFFICIENT
    STATUSCODE_BADHISTORYOPERATIONINVALID
    STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED
    STATUSCODE_BADINVALIDTIMESTAMPARGUMENT
    STATUSCODE_BADWRITENOTSUPPORTED
    STATUSCODE_BADTYPEMISMATCH
    STATUSCODE_BADMETHODINVALID
    STATUSCODE_BADARGUMENTSMISSING
    STATUSCODE_BADNOTEXECUTABLE
    STATUSCODE_BADTOOMANYSUBSCRIPTIONS
    STATUSCODE_BADTOOMANYPUBLISHREQUESTS
    STATUSCODE_BADNOSUBSCRIPTION
    STATUSCODE_BADSEQUENCENUMBERUNKNOWN
    STATUSCODE_BADMESSAGENOTAVAILABLE
    STATUSCODE_BADINSUFFICIENTCLIENTPROFILE
    STATUSCODE_BADSTATENOTACTIVE
    STATUSCODE_BADALREADYEXISTS
    STATUSCODE_BADTCPSERVERTOOBUSY
    STATUSCODE_BADTCPMESSAGETYPEINVALID
    STATUSCODE_BADTCPSECURECHANNELUNKNOWN
    STATUSCODE_BADTCPMESSAGETOOLARGE
    STATUSCODE_BADTCPNOTENOUGHRESOURCES
    STATUSCODE_BADTCPINTERNALERROR
    STATUSCODE_BADTCPENDPOINTURLINVALID
    STATUSCODE_BADREQUESTINTERRUPTED
    STATUSCODE_BADREQUESTTIMEOUT
    STATUSCODE_BADSECURECHANNELCLOSED
    STATUSCODE_BADSECURECHANNELTOKENUNKNOWN
    STATUSCODE_BADSEQUENCENUMBERINVALID
    STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED
    STATUSCODE_BADCONFIGURATIONERROR
    STATUSCODE_BADNOTCONNECTED
    STATUSCODE_BADDEVICEFAILURE
    STATUSCODE_BADSENSORFAILURE
    STATUSCODE_BADOUTOFSERVICE
    STATUSCODE_BADDEADBANDFILTERINVALID
    STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE
    STATUSCODE_UNCERTAINLASTUSABLEVALUE
    STATUSCODE_UNCERTAINSUBSTITUTEVALUE
    STATUSCODE_UNCERTAININITIALVALUE
    STATUSCODE_UNCERTAINSENSORNOTACCURATE
    STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED
    STATUSCODE_UNCERTAINSUBNORMAL
    STATUSCODE_GOODLOCALOVERRIDE
    STATUSCODE_BADREFRESHINPROGRESS
    STATUSCODE_BADCONDITIONALREADYDISABLED
    STATUSCODE_BADCONDITIONALREADYENABLED
    STATUSCODE_BADCONDITIONDISABLED
    STATUSCODE_BADEVENTIDUNKNOWN
    STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE
    STATUSCODE_BADDIALOGNOTACTIVE
    STATUSCODE_BADDIALOGRESPONSEINVALID
    STATUSCODE_BADCONDITIONBRANCHALREADYACKED
    STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED
    STATUSCODE_BADCONDITIONALREADYSHELVED
    STATUSCODE_BADCONDITIONNOTSHELVED
    STATUSCODE_BADSHELVINGTIMEOUTOFRANGE
    STATUSCODE_BADNODATA
    STATUSCODE_BADBOUNDNOTFOUND
    STATUSCODE_BADBOUNDNOTSUPPORTED
    STATUSCODE_BADDATALOST
    STATUSCODE_BADDATAUNAVAILABLE
    STATUSCODE_BADENTRYEXISTS
    STATUSCODE_BADNOENTRYEXISTS
    STATUSCODE_BADTIMESTAMPNOTSUPPORTED
    STATUSCODE_GOODENTRYINSERTED
    STATUSCODE_GOODENTRYREPLACED
    STATUSCODE_UNCERTAINDATASUBNORMAL
    STATUSCODE_GOODNODATA
    STATUSCODE_GOODMOREDATA
    STATUSCODE_BADAGGREGATELISTMISMATCH
    STATUSCODE_BADAGGREGATENOTSUPPORTED
    STATUSCODE_BADAGGREGATEINVALIDINPUTS
    STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED
    STATUSCODE_GOODDATAIGNORED
    STATUSCODE_BADREQUESTNOTALLOWED
    STATUSCODE_BADREQUESTNOTCOMPLETE
    STATUSCODE_GOODEDITED
    STATUSCODE_GOODPOSTACTIONFAILED
    STATUSCODE_UNCERTAINDOMINANTVALUECHANGED
    STATUSCODE_GOODDEPENDENTVALUECHANGED
    STATUSCODE_BADDOMINANTVALUECHANGED
    STATUSCODE_UNCERTAINDEPENDENTVALUECHANGED
    STATUSCODE_BADDEPENDENTVALUECHANGED
    STATUSCODE_GOODCOMMUNICATIONEVENT
    STATUSCODE_GOODSHUTDOWNEVENT
    STATUSCODE_GOODCALLAGAIN
    STATUSCODE_GOODNONCRITICALTIMEOUT
    STATUSCODE_BADINVALIDARGUMENT
    STATUSCODE_BADCONNECTIONREJECTED
    STATUSCODE_BADDISCONNECT
    STATUSCODE_BADCONNECTIONCLOSED
    STATUSCODE_BADINVALIDSTATE
    STATUSCODE_BADENDOFSTREAM
    STATUSCODE_BADNODATAAVAILABLE
    STATUSCODE_BADWAITINGFORRESPONSE
    STATUSCODE_BADOPERATIONABANDONED
    STATUSCODE_BADEXPECTEDSTREAMTOBLOCK
    STATUSCODE_BADWOULDBLOCK
    STATUSCODE_BADSYNTAXERROR
    STATUSCODE_BADMAXCONNECTIONSREACHED

);

our $VERSION = '0.01';

require XSLoader;
XSLoader::load('OPCUA::Open62541', $VERSION);

# Preloaded methods go here.

1;
__END__
# Below is stub documentation for your module. You'd better edit it!

=head1 NAME

OPCUA::Open62541 - Perl extension for blah blah blah

=head1 SYNOPSIS

  use OPCUA::Open62541;
  blah blah blah

=head1 DESCRIPTION

Stub documentation for OPCUA::Open62541, created by h2xs. It looks like the
author of the extension was negligent enough to leave the stub
unedited.

Blah blah blah.

=head2 EXPORT

None by default.



=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

Alexander Bluhm, E<lt>bluhm@E<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2020 by Alexander Bluhm

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.30.1 or,
at your option, any later version of Perl 5 you may have available.


=cut
